apiVersion: v1
kind: Service
metadata:
  name: sandbox-service
  namespace: default
spec:
  clusterIP: None
  selector:
    app: sandbox-runner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
